config/routes.rb
Deploydapp::Application.routes.draw do
	# Devise stuff
	devise_for :users

	# The list of your deployments
	resources :deployments do
		resources :pull_requests
	end

	# OAuth callback function
	get '/auth/:provider/callback' => 'authentications#create'

	# Authentications controller routes
	resources :authentications

	# DeployableApplications controller routes
	resources :deployable_applications do 
		resources :deployments
	end

	resources :general_settings do
		post 'update'
	end

	# Include api routes
	draw :api

	root :to => "deployable_applications#index"

end

app/views/partials/_navbar.html.erb
<nav id="app_main_navigation" class="navbar navbar-fixed-top da-navbar" role="navigation">

	<div class="container">

		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<%= link_to '<i class="glyphicon glyphicon-arrow-left"></i>'.html_safe, :back, :class=>"navbar-brand navbar-back-btn" %>
			<%= link_to root_url, :class => "navbar-brand" do %>
				Captain
				<% if @deployable_application.present? %>
					<span class='label label-<%= (@deployable_application.installed?) ? 'success' : 'danger' %> deployable-application'>
						<%= "#{@deployable_application.name}" %>
					</span>
				<% end %>
			<% end %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">

			<% if user_signed_in? %>

				<ul class="nav navbar-nav">
					<li>
						<%= link_to deployable_applications_url do %>
							<span class="glyphicon glyphicon-tasks"></span>
							Your applications
						<% end %>
					</li>
					<li>
						<%= link_to authentications_url do %>
							<span class="glyphicon glyphicon-user"></span>
							Your account
						<% end %>
					</li>
				</ul>

				<div class="navbar-right">
					<p class="navbar-text">
						<%= content_tag :b, current_user.profile_name %>, Not you?
						<%= link_to "Sign out", destroy_user_session_url, :method => :delete %>
					</p>
				</div>

			<% else %>

				<%= link_to "Get on board", authentications_url, :class => "btn btn-primary btn-outline navbar-btn" %>
				
			<% end %>

		</div><!-- /.navbar-collapse -->


	</div>

</nav>

app/views/partials/_timeline_with_deployments.html.erb
<% deployments ||= [] %>

<div class="feed-group timeline">

	<% deployments.each do |deployment| %>
		<div class="feed-element">
			<span class="feed-bullet">
				<span class="bullet-label"><%= formatted_time deployment.created_at %></span>
			</span>

			<div class="feed-body">
				
				<% if deployment.has_author? %>
					<div class="feed-avatar">
						<%= image_tag avatar_url(deployment.author_email) %>
					</div>
				<% end %>

				<h5 class="feed-title">
					<%= link_to "#{deployment.author_name} deployed #{deployment.title}", deployable_application_deployment_url(@deployable_application, deployment, public_token_param) %>

					<small class="small-suggestion">
						<%= "#{time_ago_in_words(deployment.created_at).capitalize} ago" %>
					</small>
				</h5>

				<div>
					<div>
						<p>
							<%= deployment.description %>
						</p>
					</div>

					<hr>

					<!-- Pull requests -->
					<div>
						<% if deployment.pull_requests.any? %>
							<div>
								<strong>Pull requests: </strong>
							</div>
							<% deployment.pull_requests.first(5).each do |pull_request| %>
								<a href="<%= deployment_pull_request_url deployment, pull_request %>">
									<strong>#<%= pull_request.pid %></strong>
									<%= pull_request.title %>
								</a>
							<% end %>

							<% if deployment.pull_requests.count > 5 %>
								<div>
									<a href="<%= deployable_application_deployment_url(@deployable_application, deployment) %>">
										See other <%= deployment.pull_requests.count - 5 %> pull requests
									</a>
								</div>
							<% end %>
						<% else %>
							<div class="alert alert-warning alert-sm">
								No deployed pull requests
							</div>
						<% end %>

					</div>
					
				</div>
				
			</div>
			
		</div>
	<% end %>

</div>