config/routes.rb
Deploydapp::Application.routes.draw do
	# Devise stuff
	devise_for :users

	# The list of your deployments
	resources :deployments do
		resources :pull_requests
	end

	# OAuth callback function
	get '/auth/:provider/callback' => 'authentications#create'

	# Authentications controller routes
	resources :authentications

	# DeployableApplications controller routes
	resources :deployable_applications do 
		resources :deployments
	end

	resources :general_settings do
		post 'update'
	end

	# Include api routes
	draw :api

	root :to => "deployable_applications#index"

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < BaseController
	before_action :set_authentication, only: [:show, :edit, :update, :destroy]

	# GET /authentications
	# GET /authentications.json
	def index
		@authentications = Authentication.all
	end

	# GET /authentications/1
	# GET /authentications/1.json
	def show
	end

	# GET /authentications/new
	def new
		@authentication = Authentication.new
	end

	# GET /authentications/1/edit
	def edit
	end

	# POST /authentications
	# POST /authentications.json
	def create

		@auth = request.env["omniauth.auth"]

		provider      = @auth.provider
		uid           = @auth.uid
		access_token  = @auth.credentials.token
		token_secret  = @auth.credentials.secret
		consumer_key  = ""
		consumer_secret  = ""

		if provider == "bitbucket"
			consumer_key = @auth.extra.access_token.consumer.key
			consumer_secret = @auth.extra.access_token.consumer.secret
		end

		@authentication = Authentication.find_by_provider_and_uid(provider, uid)

		if @authentication.present?
			# The authentication is already there
			# Get the user
			user = @authentication.user

			# And sign him in
			flash[:notice] = "Signed in successfully"
			sign_in_and_redirect :user, user

		elsif current_user.present?
			# There's no authentication in db, but the user is present

			# Create an authentication for the user and redirect
			current_user.authentications.create! :provider => provider, 
												 :uid => uid, 
												 :access_token => access_token,
												 :token_secret => token_secret,
												 :consumer_key => consumer_key,
												 :consumer_secret => consumer_secret
			redirect_to deployable_applications_url, :notice => "Successfully added authentication."

		else

			redirect_to new_user_registration_url and return

			# Uncomment this to make the user log in with integrations

			# # There is no @auth and no user
			# # So create a new user
			# user = User.new

			# # Create an authentication for the new user
			# user.apply_omniauth(@auth)

			# if user.save
			# 	# Sign him in if no errors
			# 	flash[:notice] = "Signed in successfully"
			# 	flash[:just_signed_up] = true
			# 	sign_in_and_redirect :user, user
			# else
			# 	# Complete registration if any errors
			# 	session[:omniauth] = @auth.except('extra')
			# 	redirect_to new_user_registration_url
			# end
		end

	end

	# PATCH/PUT /authentications/1
	# PATCH/PUT /authentications/1.json
	# def update
	#   respond_to do |format|
	#     if @authentication.update(authentication_params)
	#       format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
	#       format.json { head :no_content }
	#     else
	#       format.html { render action: 'edit' }
	#       format.json { render json: @authentication.errors, status: :unprocessable_entity }
	#     end
	#   end
	# end

	# DELETE /authentications/1
	# DELETE /authentications/1.json
	def destroy
		@authentication = current_user.authentications.find(params[:id])
		@authentication.destroy
		
		respond_to do |format|
			format.html { 
				redirect_to authentications_url, :notice => "Successfully destroyed authentication." 
			}
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_authentication
			@authentication = Authentication.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def authentication_params
			params.require(:authentication).permit(:user_id, :provider, :uid, :access_token)
		end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= form_for(@authentication) do |f| %>
  <% if @authentication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

      <ul>
      <% @authentication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<% content_for :title do %>
	<%= title "Your authentications", :wrapper_class => "" %>
	<%= sub_title "Your connections to your repos" %>
<% end %>

<table class="table">
	<thead>
		<tr>
			<th>Provider</th>
			<th></th>
		</tr>
	</thead>

	<tbody>
		<% @authentications.each do |authentication| %>
			<tr>
				<td><%= authentication.provider.capitalize %></td>
				<td>
					<%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<% content_for :title do %>
	<%= title "Add an SCM", :wrapper_class => "" %>
	<%= sub_title "Select your service" %>
<% end %>

<div class="row">
	<div class="col-lg-3">
		<a class="thumbnail" href="<%= auth_url(:bitbucket) %>">
			<%= image_tag "scm-logos/bitbucket-logo.png", :class => "img-responsive", :style => "padding: 2em; width: 100%;"%>
		</a>
	</div>
</div>
<br>
<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @authentication.user_id %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @authentication.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @authentication.uid %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @authentication.access_token %>
</p>

<p>
  <strong>Token secret:</strong>
  <%= @authentication.token_secret %>
</p>

<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>