config/routes.rb
Deploydapp::Application.routes.draw do
	# Devise stuff
	devise_for :users

	# The list of your deployments
	resources :deployments do
		resources :pull_requests
	end

	# OAuth callback function
	get '/auth/:provider/callback' => 'authentications#create'

	# Authentications controller routes
	resources :authentications

	# DeployableApplications controller routes
	resources :deployable_applications do 
		resources :deployments
	end

	resources :general_settings do
		post 'update'
	end

	# Include api routes
	draw :api

	root :to => "deployable_applications#index"

end

app/models/deployment.rb
class Deployment < ActiveRecord::Base
	
	# For now each user has many deployments and one app
	belongs_to :user

	# The application the user is deploying
	belongs_to :deployable_application

	# Has many associated pull requests
	has_many :pull_requests

	# Returns the title and if no title has been added returns a fallback
	def title
		self[:title] || "Deployment ##{id}"
	end

	# Returns the description and if no description has been added returns a fallback
	def description
		self[:description] || "No description added"
	end

	# Returns the author of the deploy and if no author has been added returns a fallback
	def author_name
		self[:author_name] || "Someone"
	end

	def author_email=(email)
		self[:author_email] = email.gsub("\n", "")
	end

	def author_email
		self[:author_email].gsub("\n", "")
	end

	def has_author?
		self[:author_name].present?
	end

	def repo_name
		match :repo_name
	end

	def repo_owner
		match :repo_owner
	end

	private
		def match(value)
			response = nil

			# REGEX => ^https?:\/\/(\w+)@(\w+)\.(org|it|com|net)\/(\w+)\/([\w\.]+).(git)$
			# 			1. Repo user
			# 			2. Provider (github, bitbucket etc.)
			# 			3. Domain
			# 			4. Repo owner
			# 			5. Repo name
			# 			6. Extension (git or others)

			regex = /^https?:\/\/(\w+)@(\w+)\.(org|it|com|net)\/(\w+)\/([\w\.]+).(git)$/

			result = regex.match repo

			response = result[1] 				if value == :repo_user
			response = result[2] 				if value == :repo_provider
			response = result[2] + result[3] 	if value == :repo_provider_domain
			response = result[4] 				if value == :repo_owner
			response = result[5] 				if value == :repo_name
			response = result[6] 				if value == :repo_extension

			response
		end
end

app/controllers/api/v1/deployments_controller.rb
class Api::V1::DeploymentsController < Api::V1::BaseController

	include ExceptionsHelper

	# before_action :set_deployment, only: [:show, :edit, :update, :destroy]

	# POST /deployments
	# POST /deployments.json
	def create
		@app 				= find_deployable_application_by("public_token", params[:deployment][:deployable_application_id])

		# Chech if the branch and the environment are correct, otherwise kill the request with raise HTTPUnauthorized
		validate_branch_and_environment(@app, params)


		# CREATE NEW RAKE DEPLOY
		@deployment 		= @app.deployments.create!(deployment_params)

		RakeInvoker.run(pull_requests: :fetch_for_app, PUBLIC_TOKEN: @app.public_token, APP_ID: @app.id, DEPLOYMENT_ID: @deployment.id)

		# @deployment.user 	= User.first

		if @deployment.save
			render :json => "Done"
		else
			render :json => "Errors"
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		# def set_deployment
		#	@deployment = Deployment.find(params[:id])
		# end

		# Never trust parameters from the scary internet, only allow the white list through.
		def deployment_params
			params.require(:deployment).permit(:branch, :environment, :revision, :repo, :author_name, :author_email)
		end

		# Check if deploy branch are equals to settings
		def validate_branch_and_environment(app, params)
			unless @app.branch == params[:deployment][:branch] && @app.environment == params[:deployment][:environment]
				raise HTTPUnauthorized
			end
		end

end

app/controllers/deployments_controller.rb
class DeploymentsController < BaseController
	# must be logged in
	before_filter :scm_associate_user!

	before_action :set_deployable_application, only: [:show, :edit, :update, :destroy]


	# GET /deployments
	# GET /deployments.json
	def index

		app_id = params[:deployable_application_id] || current_user.deployable_applications.first.id

		if deployable_application_id = app_id
			@deployable_application = DeployableApplication.find_by_id(deployable_application_id)
			@deployments = @deployable_application.deployments.order(:created_at => :desc)
		else
			@deployments = Deployment.none
		end
	end

	# GET /deployments/1
	# GET /deployments/1.json
	def show
		respond_to do |format|
			format.html {  }
			format.json { render json: @deployment }
		end

	end

	# GET /deployments/new
	# def new
	# 	@deployment = Deployment.new
	# end

	# POST /deployments
	# POST /deployments.json
	# def create
	# 	@deployment = Deployment.new(deployment_params)

	# 	respond_to do |format|
	# 		if @deployment.save
	# 			format.html { redirect_to @deployment, notice: 'Deployment was successfully created.' }
	# 			format.json { render action: 'show', status: :created, location: @deployment }
	# 		else
	# 			format.html { render action: 'new' }
	# 			format.json { render json: @deployment.errors, status: :unprocessable_entity }
	# 		end
	# 	end
	# end

	# PATCH/PUT /deployments/1
	# PATCH/PUT /deployments/1.json
	def update
		respond_to do |format|
			if @deployment.update(deployment_params)
				format.html { redirect_to @deployment, notice: 'Deployment was successfully updated.' }
				format.json { head :no_content }
			else
				format.html { render action: 'edit' }
				format.json { render json: @deployment.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /deployments/1
	# DELETE /deployments/1.json
	def destroy
		@deployment.destroy
		respond_to do |format|
			format.html { redirect_to deployments_url }
			format.json { head :no_content }
		end
	end

	private
		def set_deployable_application
			if deployable_application_id = params[:deployable_application_id]
				@deployable_application = DeployableApplication.find_by_id(deployable_application_id)
			else
				@deployable_application = Deployment.find_by_id(params[:id]).deployable_application
			end

		end
		# Use callbacks to share common setup or constraints between actions.
		# def set_deployment
		# 	if deployable_application_id = params[:deployable_application_id]
		# 		@deployable_application = DeployableApplication.find_by_id(deployable_application_id)
		# 		@deployment = @deployable_application.deployments.find(params[:id])
		# 	else
		# 		@deployment = Deployment.find(params[:id])
		# 	end
		# end

		# Never trust parameters from the scary internet, only allow the white list through.
		def deployment_params
			params.require(:deployment).permit(:title, :description, :author_name, :author_email)
		end
end

app/helpers/deployments_helper.rb
module DeploymentsHelper

	def deployment_title(deployment)
		title_regex(deployment.title, deployment.deployable_application.name).html_safe
	end

	def deployment_subtitle(deployment)
		description = deployment.description

		description = description.gsub("\n", "<br>")

		description.html_safe
	end

	def formatted_time(date)
		date.strftime "%d %b %Y %H:%M"
	end

	private 

	def title_regex(title, suffix="")
		regex = /(v([\d]\.?)+)/
		
		title.gsub(regex) {|v| "<small class='text-info'>#{v} #{suffix}</small>"}
	end
end

app/views/deployments/_form.html.erb
<%= simple_form_for(@deployment) do |f| %>

	<%= display_errors!(@deployment) %>

	<%= f.input :title %>
	<%= f.input :description %>
	<%= f.input :author_name %>
	<%= f.input :author_email %>

	<%= btn_container do %>
		<%= f.button :submit, :class => "btn-primary" %>
	<% end %>
<% end %>

app/views/deployments/edit.html.erb
<h1>Editing deployment</h1>

<%= render 'form' %>

<%= link_to 'Show', @deployment %> |
<%= link_to 'Back', :back %>

app/views/deployments/index.html.erb
<% content_for :title do %>
	<%= title "#{@deployable_application.name}", :wrapper_class => "" %>
	<%= sub_title "Listing all deployments" %>
<% end %>

<!-- Side header table -->
<% content_for :header_sidebar do %>
	
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>Repo</th>
				<th>Token</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td><%= @deployable_application.repo_owner %> <%= @deployable_application.repo_name %></td>
				<td><%= @deployable_application.public_token %></td>
			</tr>
		</tbody>
	</table>


	<!-- Actions -->
	<% if can? :update, :deployments %>
		<div class="btn-group">
			<!-- Public deployment link -->
			<%= link_to deployable_application_deployments_url(@deployable_application, :public_token => @deployable_application.public_token), :target => :blank, :class => "btn btn-primary btn-outline-inverse btn-sm" do %>
				<i class="glyphicon glyphicon-link"></i> Public link
			<% end %>
		</div>
	<% end %>


<% end %>


<% if @deployments.any? %>

	<div class="row">
		<div class="col-sm-8">
			<%= render :partial => "partials/timeline_with_deployments", :locals => {deployments: @deployments } %>
		</div>
	</div>
<% end %>

app/views/deployments/new.html.erb
<h1>New deployment</h1>

<%= render 'form' %>

<%= link_to 'Back', deployments_path %>

app/views/deployments/show.html.erb
<!-- Deployment title -->
<% content_for :title do %>
	<%= title deployment_title(@deployment), :wrapper_class => "" %>
	<%= sub_title deployment_subtitle(@deployment) %>
<% end %>

<!-- Side header table -->
<% content_for :header_sidebar do %>
	
	<table class="table table-condensed">
		<thead>
			<tr>
				<th>App</th>
				<th>Deployed at</th>
				<th>Environment</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td><%= link_to @deployable_application.name, deployable_application_url(@deployable_application) %></td>
				<td><%= formatted_time @deployment.created_at %></td>
				<td><%= @deployment.environment %> at <%= @deployment.branch %></td>
			</tr>
		</tbody>
	</table>

	<!-- Actions -->
	<% if can? :update, :deployments %>
		<div class="btn-group">
			<!-- Edit deployment link -->
			<%= link_to edit_deployment_url(@deployment), :class => "btn btn-primary btn-outline-inverse btn-sm" do %>
				<i class="glyphicon glyphicon-pencil"></i> Edit information
			<% end %>

			<!-- Public deployment link -->
			<%= link_to deployment_url(@deployment, :public_token => @deployable_application.public_token), :target => :blank, :class => "btn btn-primary btn-outline-inverse btn-sm" do %>
				<i class="glyphicon glyphicon-link"></i> Public link
			<% end %>
		</div>
	<% end %>


<% end %>


<div class="row">
	<div class="col-sm-8">
		<div class="panel panel-default panel-body">
		    <div id="disqus_thread"></div>
		    <script type="text/javascript">
		        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
		        var disqus_shortname = 'captainrb'; // required: replace example with your forum shortname
		        var disqus_url = "<%= deployment_url @deployment %>";

		        /* * * DON'T EDIT BELOW THIS LINE * * */
		        (function() {
		            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		        })();
		    </script>
		    <noscript>Please enable JavaScript to view the comments</noscript>
		    <div class="dsq-brlink">Loading comments</div>
		</div>

	</div>

	<% if @deployment.pull_requests.any? %>
		<div class="col-sm-4">
			<!-- List of pull requests -->
			<div class="panel panel-default">
				<!-- Default panel contents -->
				<div class="panel-heading"><h3 class="panel-title">Deployed pull requests</h3></div>

				<div class="list-group">
					<% @deployment.pull_requests.each do |pull_request| %>
						<a href="<%= deployment_pull_request_url @deployment, pull_request %>" class="list-group-item">
							<!-- <span class="badge"><%= pull_request.merged_on %></span> -->
							<small>#<%= pull_request.pid %> <%= pull_request.title %></small>
						</a>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>

</div>

<%= link_to 'Back', deployable_application_deployments_url(@deployable_application, public_token_param) %>